### PR TITLE
Fix/contract initialization and deploy

### LINKED ISSUE #615: fix new contract deployment
The new proposed contracts in `v0.12` aren't deployed.

### PR DESCRIPTION
**Pull request by 0x3bfc**
closes #615

### CODE REVIEW

File: scripts/deploy/truffle-wrapper/deploy/initializeContracts.js [hunk 1]
```diff
@@ -194,6 +194,22 @@ async function initializeContracts({
         }
     }
 
+    if (getAddress('ConditionStoreManager') &&
+        getAddress('AgreementStoreManager')) {
+        if (contracts.indexOf('ComputeExecutionCondition') > -1) {
+            addressBook.AccessSecretStoreCondition = zosCreate({
```
Comment (H34D) [inline scripts/deploy/truffle-wrapper/deploy/initializeContracts.js]: this should be addressBook.ComputeExecutionCondition

File: scripts/deploy/truffle-wrapper/deploy/initializeContracts.js [hunk 2]
```diff
@@ -216,6 +232,28 @@ async function initializeContracts({
         }
     }
 
+    if (getAddress('AgreementStoreManager') &&
+        getAddress('DIDRegistry') &&
+        getAddress('ComputeExecutionCondition') &&
+        getAddress('LockRewardCondition') &&
+        getAddress('EscrowReward')) {
+        if (contracts.indexOf('EscrowComputeExecutionTemplate') > -1) {
+            addressBook.EscrowAccessSecretStoreTemplate = zosCreate({
```
Comment (H34D) [inline scripts/deploy/truffle-wrapper/deploy/initializeContracts.js]: this should be `addressBook.EscrowComputeExecutionTemplate`
